# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcefb5ae37312e9c9a17025c12e905d3facfb8f399a5126d12a875460d34547e99c1fee08ce1b2a3560e02d7381e5561ab005d4f6c6c904b31affaaca143533f

test:
  secret_key_base: 2922e6696686a4c26ce08796558d2231256176b02d3f3b6b22f6c9c4a57f1b150ccd3b955ca4bd6f8a226cbd33b8569fbc15c322f75a6badd0d87a627257fe46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
